### ISSUE TITLE
Fix typo for linux compatibility

### ISSUE THREAD

**Issue by Paolo97Gll** [kmpelectronics/Arduino#10]
Change `#include "arduino.h"` to `#include "Arduino.h"` to fix linux compatibility.

See here: https://github.com/kmpelectronics/Arduino/blob/fc7978ec2476c6f9c681a76fb98092bee8c36875/ProDinoESP32/src/ProDinoESP32/src/MCP23S08.h#L15

Example of failed build:

![immagine](https://user-images.githubusercontent.com/49845775/144886457-2d266322-dba6-4e40-ac3c-7a5e93b9546f.png)

With the proposed fix, everything work

**Comment by kmpelectronics** [comment]
Thank you Paolo :)
We've fixed the code as suggested.
