### ISSUE TITLE
Trying to execute KMPDinoWiFiESP.init() crashes the system [SOLVED]

### ISSUE THREAD

**Issue by amontefusco** [kmpelectronics/Arduino#3]
Same problem here see (https://github.com/kmpelectronics/Arduino/issues/1).

I followed your procedure for flashing and setting the environment and attempted to load your examples but it keeps crashing into KMPDinoWiFiESP.init() whatever examples I try.

I have PRODINo WiFi ESP8266 V1.0

Working on Ubunto with Arduino IDE 1.8.1

Exception (9):
epc1=0x40202a36 epc2=0x00000000 epc3=0x00000000 excvaddr=0x3ffef39d depc=0x00000000

ctx: cont
sp: 3fff0280 end: 3fff0500 offset: 01a0

            stack>>>
            3fff0420: feefeffe feefeffe feefeffe feefeffe
            3fff0430: feefeffe feefeffe feefeffe 3ffef3b8
            3fff0440: 00000003 3ffef38d 3ffef39d 40202af6
            3fff0450: feefeffe feefeffe 3fff1474 40201cf9
            3fff0460: 3ffef3b8 00000001 00000001 00000bb8
            3fff0470: 00000001 3ffef38d 3ffef39d 402024b2
            3fff0480: 3fffdad0 00000004 3ffef38c 402025e1
            3fff0490: 3fffdad0 3ffef38c 00000001 4020263a
            3fff04a0: 3fffdad0 3ffef38c 3ffef3b8 402026a5
            3fff04b0: 3fffdad0 00000000 3ffef4ac 40201f53
            3fff04c0: feefeffe feefeffe feefeffe feefeffe
            3fff04d0: feefeffe feefeffe feefeffe 3ffef4d8
            3fff04e0: 3fffdad0 00000000 3ffef4d1 402065fc
            3fff04f0: feefeffe feefeffe 3ffef4e0 40100718
            <<<stack<<<

ets Jan 8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld

**Comment by amontefusco** [comment]
It crashes into SPI.transferBytes.

```
uint8_t KMPDinoWiFiESPClass::ExpanderReadRegister(uint8_t address)
{
	_expTxData[0] = READ_CMD;
	_expTxData[1] = address;

 	digitalWrite(CS, LOW);
>>>>	SPI.transferBytes(_expTxData, _expRxData, 3);
```

**Comment by amontefusco** [comment]
There is a specific prerequisite for SPI library ?

I am currently using the one into esp8266

packages/esp8266/hardware/esp8266/2.3.0/libraries/SPI/SPI.cpp

from

http://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by kmpelectronics** [comment]
Hi,

Please, try compile code on a computer with Windows.
Our clients have got a similar problem.
Our friend fixed it but we don't sure whether his pull request merged with ESP master.

Regards,
KMP Electronics LTD
Support team

**Comment by amontefusco** [comment]
I don't have any Windows at hand.
Which is the patch to be applied to esp8266 ?

**Comment by amontefusco** [comment]
The problem is not related to the ESP8266 master but to this fix user piflav made on Oct 8:

[SPI::transferBytes should handle unaligned buffers #3315](https://github.com/kmpelectronics/Arduino/commit/723a7b192a5205c0c751cb2db9410d5c6d7ffc06#diff-6f90b6204ec8c44fc7e31a9617f76ea9)

so, cloning with GitHub tools your repo made the trick.

**Comment by kmpelectronics** [comment]
This fix should be resolve the problems with no Windows system. I am gong to create a new zip library.

**Comment by amontefusco** [comment]
Ok, now it is the most recent.
BTW you even fixed the format  leaving into the .zip just the right directory (the previous file contained all the tree).
Many thanks for the support.

**Comment by kmpelectronics** [comment]
Many thanks for your help!
We glad for people as you. :)

Regards,
KMP Electronics LTD
