### ISSUE TITLE
ProDiNo Ethernet MQTT

### ISSUE THREAD

**Issue by vukomir** [kmpelectronics/Arduino#4]
Hi,

can you publish a example of MQTT implementation for ProDiNo Ethernet?

Thanks.
Br,
Vuko

**Comment by kmpelectronics** [comment]
Hello Vuko,

Thanks for your suggestion. We are going to add MQTT examples for ProDiNo Ethernet after Christmas holidays.

Regards,
Plamen Kovandjiev
KMP Electronics Ltd.

**Comment by kmpelectronics** [comment]
Hello Vuko,

MQTT example for ProDiNo Ethernet has been added.
You can see it here: https://github.com/kmpelectronics/Arduino/tree/master/KMPDinoEthernet/src/KMPDinoEthernet/examples/MqttSimple

Regards,
Plamen Kovandjiev
KMP Electronics Ltd.
