### ISSUE TITLE
ethernet WebRelay example get and post

### ISSUE THREAD

**Issue by v8star** [kmpelectronics/Arduino#7]
Hi, 

there is the possiblity to control and get status of the relay by submit commands (maybe from openhab) with this sketch?

https://github.com/kmpelectronics/Ethernet/blob/master/examples/WebServer/WebServer.ino

My goal is to replace all souliss stuff due to no reliability of openhab souliss binding.

thanks

**Comment by kmpelectronics** [comment]
Hello,
I don't fully understand what is your idea. If you use TCP you can use this example:
[https://github.com/kmpelectronics/Arduino/blob/master/KMPDinoEthernet/src/KMPDinoEthernet/examples/TcpRelay/TcpRelay.ino](url)
if you want use HTTP you can return JSON request with statuses.

Regards,
Plamen Kovandjiev

**Comment by v8star** [comment]
Hello, i try to explain my situation better:
actually i manage two prodino2 eth with souliss and hopenhab2. Between they, there is souliss binding. I must control with openhab and not with native app because i have some trigger from other things that interact with the prodino boards. Most of time works but sometimes and randomly souliss binding lost commands with the result that i have the lights still on and the status off by the application.  Souliss mantainer try recently to fix this aspect but, for some reason me and other people still have this problem with relay with feedback.  From here my request: your tcp examples are great but TcpRelay can only set relay status and TcpOptoInput can only read: for my needs, i need a mix of both sketch. I'm not pretty sure that i can merge those two sketch Could you possibly help me? I have to deploy another two boards to cover all my needs and i'm still evalutate to continue whit this config or change road. Many thanks.

**Comment by kmpelectronics** [comment]
Hello,
Can you write me on an email: contact@kmpelectronics.eu 

Regards, Plamen
