### ISSUE TITLE
First time prodino lorawan

### ISSUE THREAD

**Issue by Jogger56** [kmpelectronics/Arduino#8]
Hello 
i have a problem to start. there is no com port anymore to talk to the arduino
I am traying to execute firstconfigurationv2 but get the following errors
WARNING: library MKRWAN_v2 claims to run on samd, mbed architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).

Can you help me on the way?
Thanks

![03-08-2021 16-41-01](https://user-images.githubusercontent.com/30210385/128035275-1bfbb6b2-cc9f-4373-a79a-8221e52bae75.jpg)

**Comment by kmpelectronics** [comment]
Hello,

Do you first flash:
https://github.com/kmpelectronics/Arduino/tree/master/ProDinoESP32/src/ProDinoESP32/examples/LoRa_v2/MKRWANFWUpdate_standalonev2
LoRa WAN firmware?

Then you can try with the examples.

Best regards,
Plamen Kovandjiev
Coordinator & Co-founder
KMP Electronics Ltd.
<https://kmpelectronics.eu/>

На вт, 3.08.2021 г. в 17:44 ч. Jogger56 ***@***.***> написа:

**Comment by Jogger56** [comment]
Hello Plamen
i do have now the programmer but as you can see it does not fit into the board.
Any proposal how to solve this?

Thanks Jo

[cid:37de74e6-c987-42a4-9235-a3f482ab4dba]

________________________________
