### ISSUE TITLE
Ethernet not responding for 5~50 secs after reboot

### ISSUE THREAD

**Issue by wildstray** [kmpelectronics/Arduino#9]
I'm experiencing this issue: when I reboot, Ethernet is responding for two seconds, then not responding for a variable time of 5~50 seconds, then responding again.

```
PING 10.1.1.254 (10.1.1.254) 56(84) bytes of data.
64 bytes from 10.1.1.254: icmp_seq=1 ttl=128 time=0.074 ms
64 bytes from 10.1.1.254: icmp_seq=2 ttl=128 time=0.126 ms
64 bytes from 10.1.1.254: icmp_seq=3 ttl=128 time=0.112 ms
64 bytes from 10.1.1.254: icmp_seq=4 ttl=128 time=0.118 ms
64 bytes from 10.1.1.254: icmp_seq=5 ttl=128 time=0.116 ms
64 bytes from 10.1.1.254: icmp_seq=6 ttl=128 time=0.074 ms

64 bytes from 10.1.1.254: icmp_seq=16 ttl=128 time=0.237 ms
64 bytes from 10.1.1.254: icmp_seq=17 ttl=128 time=0.108 ms

64 bytes from 10.1.1.254: icmp_seq=51 ttl=128 time=0.119 ms
64 bytes from 10.1.1.254: icmp_seq=52 ttl=128 time=0.149 ms
64 bytes from 10.1.1.254: icmp_seq=53 ttl=128 time=0.073 ms
64 bytes from 10.1.1.254: icmp_seq=54 ttl=128 time=0.073 ms
64 bytes from 10.1.1.254: icmp_seq=55 ttl=128 time=0.126 ms
```
This issue can be reproduced also with the simplest code from scratch...

```
#include <Ethernet.h>
byte _mac[6] = {0};
IPAddress ip (10,1,1,254);
IPAddress subnet (255,255,255,0);
IPAddress gateway (10,1,1,1);
IPAddress dns (10,1,1,1);

void setup()
{
    Serial.begin(115200);
    esp_read_mac(_mac, ESP_MAC_ETH);
    Ethernet.begin(_mac, ip, dns, gateway, subnet);
}
```

**Comment by wildstray** [comment]
Additional information: the platform I'm using is ProDino ESP32 Ethernet, I take for granted the KMPProDinoESP32.begin(ProDino_ESP32_Ethernet); also if I didn't mentioned it in the code.

**Comment by kmpelectronics** [comment]
We've tested the problem with our example: [WebRelayWE](https://github.com/kmpelectronics/Arduino/blob/master/ProDinoESP32/src/ProDinoESP32/examples/WebRelayWE/WebRelayWE.ino) but we didn't achieve behavior described above.
Here you can see the video from our [test](https://drive.google.com/uc?id=1n5VHYmIQoToGRAl-g5g2NEMKf27_Hj-Q)
Out steps were:
1. We start `ping` in a console. We see that **PRODINo ESP32 Ethernet** is pinging.
2. We restart **PRODINo ESP32 Ethernet** and we see `Request timed out.`
3. When **PRODINo ESP32 Ethernet** starts we see normal ping again without any brake in the communication.

**Comment by wildstray** [comment]
Ok, but for me is always reproducible. Would you try with a fixed ip address, please? The issue appears only with fixed network parameters.

**Comment by kmpelectronics** [comment]
We tried also with static IP Address. You can see it in the [video](https://drive.google.com/uc?id=1_TVDKS3K6J6Kq3MxHex8wGwaV06sal8g). We exactly used our example: [WebRelayWE](https://github.com/kmpelectronics/Arduino/blob/master/ProDinoESP32/src/ProDinoESP32/examples/WebRelayWE/WebRelayWE.ino) with static IP address in this case it is `192.168.1.197`. We used board: **PRODINo ESP32 Ethernet**. We didn't reproduce your behavior. 
I recall something... Will you check your network there is the same IP address you use in your device?

**Comment by wildstray** [comment]
Ok, found that the issue was caused by spanning tree, turning it off on the switch the issue disappeared. Excuse me for bothering you!
